# Generated by Django 3.1.4 on 2021-01-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
